config/routes.rb
Dashboard::Application.routes.draw do
  get "dashboard/index"
  get "cars/index"

  resources :widgets do
    member do
      match 'proxy',       :to => Widget::Proxy
      match 'proxy/*path', :to => Widget::Proxy
      get   '*resource'    => 'widgets#static'
    end
  end

end

app/models/widget.rb
class Widget
  class Proxy
    def self.call(env)
      name = env["PATH_INFO"].match(/\/widgets\/(\w*)/)[1]
      proxy = ::Widget.new(name).proxy_app
      proxy.call(env)
    end
  end

  attr_accessor :name
  def initialize(name)
    @name = name
  end

  def title
    name
  end

  def id
    SecureRandom.uuid
  end

  def render(view)
    view.render :partial => 'widgets/iframe', :locals => { :widget => self }
  end

  def base
    Rails.root.join('app', 'widgets', name)
  end

  def home_page
    base.join('index.html')
  end

  def resource(path)
    base.join(path)
  end

  def proxy_app
    load base.join('proxy.rb').to_s
    Widget::Proxy.const_get(name.capitalize).new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    respond_to do |format|
      format.js {
        html = render_to_string
        json = {"html" => html}.to_json
        callback = params[:callback]
        jsonp = callback + "(" + json + ")"
        render :text => jsonp, :content_type => "text/javascript"
      }
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @widgets = [Widget.new('ticker'), Widget.new('kittens'),
                Widget.new('flot'), Widget.new('kittens'), Widget.new('flot')]
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def show
    send_file Widget.new(params[:id]).home_page,
             :disposition => 'inline',
             :type => 'text/html'
  end

  def proxy
    proxy = Widget.new(params[:id]).proxy_app
    resp = proxy.call(request.env)
    render :nothing => true
  end

  def static
    send_file Widget.new(params[:id]).resource(params[:resource]),
             :disposition => 'inline',
             :type => 'image/jpeg'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/cars/index.html.erb
<ul>
  <li>Acura</li>
  <li>BMW</li>
  <li>Audi</li>
</ul>

app/views/dashboard/index.html.erb
<% @widgets.each_slice(@widgets.length / 2) do |widgets| %>
  <div class="sg-17">
    <% widgets.each do |widget| %>
      <div class="widget">
        <header><%= widget.title %></header>
        <%= widget.render(self) %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="wrapper">
    <div id="container">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/widgets/_iframe.html.erb
<iframe id="<%= widget.id %>" scrolling="no" src="<%= widget_path(widget.name) %>/"></iframe>